version: '3.7'
services:
  positionscrawler:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /crawler/edgar/crawler-go.py positions   "
    environment:
      - 'MONGO_URI=mongodb://13fmongo:27017'
    restart: always
    depends_on:
      - mongo
  filingindexer:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /crawler/edgar/crawler-go.py edgarindex   "
    environment:
      - 'CRAWL_YEARS=2018,2019,2020'
      - 'MONGO_URI=mongodb://13fmongo:27017'
    depends_on:
      - mongo

  stockinfo:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /crawler/edgar/crawler-go.py stockinfo   "
    environment:
      - 'CRAWL_YEARS=2018,2019,2020'
      - 'MONGO_URI=mongodb://13fmongo:27017'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: 13fmongo
    restart: always
    volumes:
     - /home/docker/13f/mongo/data/db:/data/db
    ports:
      - 27020:27017
  metabase:
    image: metabase/metabase
    container_name: edgar-metabase
    restart: always
    environment:
      - 'MB_DB_FILE=/metabase-data/metabase.db'
    volumes:
    - /home/docker/metabase-data:/metabase-data
    ports:
    - 3000:3000
    depends_on:
      - mongo
