version: '3.7'
services:
  positionscrawler:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /crawler/edgar/crawler-go.py positions   "
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
      - redis
  filingindexer:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /crawler/edgar/crawler-go.py edgarindex   "
    env_file:
      - .env
    depends_on:
      - mongo
  stockinfo:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /crawler/edgar/crawler-go.py stockinfo   "
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: always
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /crawler/edgar/edgar/redis_worker.py run"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: 13fmongo
    restart: always
    volumes:
     - /home/docker/13f/mongo/data/db:/data/db
    ports:
      - 27020:27017
  redis:
    image: redis
    ports:
      - "6379:6379"
  metabase:
    image: metabase/metabase
    container_name: edgar-metabase
    restart: always
    environment:
      - 'MB_DB_FILE=/metabase-data/metabase.db'
    volumes:
    - /home/docker/metabase-data:/metabase-data
    ports:
    - 3000:3000
    depends_on:
      - mongo
