version: '3.7'
services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'CRAWL_YEARS=2019,2020'
      - 'MONGO_URI=mongodb://13fmongo:27017'
    volumes:
      - '/home/docker/edgar/crawler/.scrapy:/crawler/edgar/.scrapy'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: 13fmongo
    restart: always
    volumes:
     - /home/docker/13f/mongo/data/db:/data/db
    ports:
      - 27020:27017
