version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: 13fes
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
    - "/home/docker/13f/es/data:/usr/share/elasticsearch/data:rw"
    external_links:
      - 13fmongo
  kibana:
    image: kibana:7.6.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


networks:
  default:
    name: 13fnet