version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: 13fes
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
    - "esdata1:/usr/share/elasticsearch"
    external_links:
      - 13fmongo
  kibana:
    image: kibana:7.6.1
    shm_size: 5g
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local

networks:
  default:
    name: 13fnet