version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: 13fes
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    external_links:
      - 13fmongo
  kibana:
    image: kibana:7.6.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
#  transport:
#    build: ./transporter
#    environment:
#      - DB_NAME=edgar
#      - MONGODB_URI=mongodb://13fmongo:27017
#      - ELASTICSEARCH_URI=y
#    depends_on:
#      - elasticsearch
#    external_links:
#      - 13fmongo
#  abc:
#    image: appbaseio/abc
#    command: 'import --src_type=mongodb --src_uri="mongodb://13fmongo:27017/edgar" "http://elasticsearch:9200/edgar"'
#    depends_on:
#      - elasticsearch
#    external_links:
#      - 13fmongo
#    entrypoint: "tail -f /dev/null"
#    command: "import"


  dejavu:
    image: appbaseio/dejavu
    ports:
    - "1358:1358"
    depends_on:
      - elasticsearch

networks:
  default:
    name: 13fnet